version: '3.7'
services:

    redis:
        container_name: redis
        build: ./redis
        restart: always
        volumes:
            - ${PWD}/redis/data:/data
#            - type: bind
#              source: ${PWD}/redis/conf.d/redis.conf
#              target: /usr/local/etc/redis/redis.conf
#        environment:
#            # ${DB_PASSWORD} берем либо из окружения, либо из
#            # .env-файла (создавать директории с docker-compose.yml)
#            REDIS_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "6379:6379" # дефолтные порты redis'а
        networks: 
            golovin:
#                ipv4_address: 172.19.0.10
                aliases: 
                    - redis_net

    mongo:
        container_name: mongo
        build: ./mongo
        restart: always
        volumes:
          - ${PWD}/mongo/data:/etc/mongo
        environment:
            # ${DB_PASSWORD} берем либо из окружения, либо из
            # .env-файла (создавать директории с docker-compose.yml)
#            MONGO_INITDB_DATABASE: golovin
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "27017:27017" # дефолтные порты mongo
        networks:
            golovin:
#                ipv4_address: 172.19.0.15
                aliases:
                    - mongo_net

    neo4j:
        container_name: neo4j
        build: ./neo4j
        restart: always
        environment:
#            # ${DB_PASSWORD} берем либо из окружения, либо из
#            # .env-файла (создавать директории с docker-compose.yml)
##            NEO4J_ROOT_PASSWORD: ${DB_PASSWORD}
            NEO4J_AUTH: none
#        volumes:
#            - ${PWD}/neo4j/conf:/conf
#            - ${PWD}/neo4j/data:/data
#            - ${PWD}/neo4j/import:/import
#            - ${PWD}/neo4j/logs:/logs
#            - ${PWD}/neo4j/metrics:/metrics
#            - ${PWD}/neo4j/plugins:/plugins
#            - ${PWD}/neo4j/ssl:/ssl
        ports:
            - "7474:7474" # дефолтные порты neo4j для HTTP
            - "7473:7473" # дефолтные порты neo4j для HTTPS
            - "7687:7687" # дефолтные порты neo4j для Bolt
        networks:
            golovin:
#                ipv4_address: 172.19.0.20
                aliases:
                    - neo4j_net

    mysql:
        container_name: mysql
        build: ./mysql
        restart: always
        environment:
            MYSQL_DATABASE: app
#            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
#            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
            - "3306:3306"
        volumes:
            # папка с созданной БД
            - ${PWD}/mysql/data:/var/lib/mysql
        networks:
            golovin:
                aliases:
                    - mysql_net

#    ms:
#        container_name: ms
#        build: ./ms
#        restart: always
#        environment:
#            # ${DB_PASSWORD} берем либо из окружения, либо из
#            # .env-файла (создавать директории с docker-compose.yml)
#            MS_ROOT_PASSWORD: ${DB_PASSWORD}
#        ports:
#            - "1433:1433" # дефолтные порты Microsoft SQL Server
#        networks:
#            golovin:
#                aliases:
#                    - ms_net

#    elastic:
#        container_name: elastic
#        build: ./elastic
#        restart: always
#        environment:
#            "discovery.type": "single-node"
#        ports:
#            - "9300:9300" # дефолтные порты ElasticSearch (для HTTPS)
#            - "9200:9200" # дефолтные порты ElasticSearch (для HTTP)
#        # зависимость от других сервисов
#        depends_on:
#          - redis
#          - mongo
#          - neo4j
#          - ms
#        links:
#          - redis
#          - mongo
#          - neo4j
#          - ms
#        networks:
#            golovin:
#                aliases:
#                    - elastic_net

    app:
        build: ./app
        container_name: app
        restart: always
        tty: true
        stdin_open: true
        volumes:
            - ${PWD}/app/repository:/var/www/app
            - ./app/conf.d:/etc/nginx/conf.d
            - type: bind
              source: ${PWD}/app/php.ini
              target: /usr/local/etc/php/conf.d/40-custom.ini
            - type: bind
              source: ${PWD}/app/logs/access.log
              target: /var/log/nginx/access.log
            - type: bind
              source: ${PWD}/app/logs/error.log
              target: /var/log/nginx/error.log
            - ./app/html:/usr/share/nginx/html
            # '.htpasswd' создавать тут: https://www.htaccesstools.com/htpasswd-generator/
            # по умолчанию: root:secret
            - type: bind
              source: ${PWD}/app/.htpasswd
              target: /etc/nginx/.htpasswd
        ports:
          - "80:80"
          - "443:443"
        # зависимость от других сервисов
        depends_on:
            - redis
            - mongo
            - neo4j
            - mysql
#            - ms
#            - elastic
        links:
            - redis
            - mongo
            - neo4j
            - mysql
#            - ms
#            - elastic
        networks:
            golovin:
#                ipv4_address: 172.19.0.5
                aliases:
                    - app_net

networks: 
    golovin:
        external: true